In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [7]:
df = pd.read_csv('Housing.csv')
df = df.select_dtypes(include=np.number)
df.head()

      price  area  bedrooms  bathrooms  stories  parking
0  13300000  7420         4          2        3        2
1  12250000  8960         4          4        4        3
2  12250000  9960         3          2        2        2
3  12215000  7500         4          2        2        3
4  11410000  7420         4          1        2        2

1. Absolute Maximum Scaling

Absolute Maximum Scaling is a feature scaling method where each value is divided by the maximum absolute value of that feature. This transformation rescales the data so that values fall within the range of −1 to 1.


Sensitive to Outliers: Extreme values can affect the maximum value and reduce scaling quality.
Best for Clean Data: Works better when the dataset does not contain strong outliers.

In [8]:
max_abs = np.max(np.abs(df), axis=0)
scaled_df = df / max_abs
scaled_df.head()

      price      area  bedrooms  bathrooms  stories   parking
0  1.000000  0.458025  0.666667       0.50     0.75  0.666667
1  0.921053  0.553086  0.666667       1.00     1.00  1.000000
2  0.921053  0.614815  0.500000       0.50     0.50  0.666667
3  0.918421  0.462963  0.666667       0.50     0.50  1.000000
4  0.857895  0.458025  0.666667       0.25     0.50  0.666667

2. Min-Max Scaling

Min-Max Scaling rescales features by subtracting the minimum value and dividing by the difference between the maximum and minimum values. This usually maps feature values to the range 0 to 1 while preserving the original distribution.

In [13]:
from sklearn.preprocessing import MinMaxScaler
df = pd.read_csv('Housing.csv')
df = df.select_dtypes(include=np.number)
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)

scaled_df.head()

      price      area  bedrooms  bathrooms   stories   parking
0  1.000000  0.396564       0.6   0.333333  0.666667  0.666667
1  0.909091  0.502405       0.6   1.000000  1.000000  1.000000
2  0.909091  0.571134       0.4   0.333333  0.333333  0.666667
3  0.906061  0.402062       0.6   0.333333  0.333333  1.000000
4  0.836364  0.396564       0.6   0.000000  0.333333  0.666667

3. Normalization (Vector Normalization)

Normalization scales each data sample so that its vector length (Euclidean norm) becomes 1. It focuses on the direction of data points rather than their magnitude, making it useful in tasks like text classification and clustering.

In [ ]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)

scaled_df.head()

   price      area      bedrooms     bathrooms       stories       parking
0    1.0  0.000558  3.007518e-07  1.503759e-07  2.255639e-07  1.503759e-07
1    1.0  0.000731  3.265305e-07  3.265305e-07  3.265305e-07  2.448979e-07
2    1.0  0.000813  2.448979e-07  1.632653e-07  1.632653e-07  1.632653e-07
3    1.0  0.000614  3.274662e-07  1.637331e-07  1.637331e-07  2.455996e-07
4    1.0  0.000650  3.505696e-07  8.764240e-08  1.752848e-07  1.752848e-07

4. Standardization (Z - Score)

Standardization scales features by subtracting the mean and dividing by the standard deviation. This transforms the data so that features have zero mean and unit variance, which helps many machine learning models perform better.

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data,
                         columns=df.columns)
print(scaled_df.head())

      price      area  bedrooms  bathrooms   stories   parking
0  4.566365  1.046726  1.403419   1.421812  1.378217  1.517692
1  4.004484  1.757010  1.403419   5.405809  2.532024  2.679409
2  4.004484  2.218232  0.047278   1.421812  0.224410  1.517692
3  3.985755  1.083624  1.403419   1.421812  0.224410  2.679409
4  3.554979  1.046726  1.403419  -0.570187  0.224410  1.517692

5. Robust Scaling

Robust Scaling scales features using the median and interquartile range (IQR) instead of the mean and standard deviation. This makes it less sensitive to outliers and skewed data, making it suitable for datasets with extreme values or noise.

In [ ]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data,
                         columns=df.columns)
print(scaled_df.head())

      price      area  bedrooms  bathrooms  stories  parking
0  3.878788  1.021739       1.0        1.0      1.0      2.0
1  3.424242  1.579710       1.0        3.0      2.0      3.0
2  3.424242  1.942029       0.0        1.0      0.0      2.0
3  3.409091  1.050725       1.0        1.0      0.0      3.0
4  3.060606  1.021739       1.0        0.0      0.0      2.0